### ISSUE TITLE
(°C ) Lockscreen weather bug - Version 3.1.1

### ISSUE THREAD

**Issue by SethWiiPlaza** [ginsudev/Dodo#2]
Dear Master Ginsu,

Congrats on the beautiful tweak. Would it be possible to display the temperature In Fahrenheit instead of Celsius? Please help I'm a stupid American. 

Thanks Again,
Seth@WiiPlaza 
![image](https://user-images.githubusercontent.com/8001327/209368181-8aafbdaf-af2b-49c1-abf5-2fb8f7a3ebfc.jpeg)

**Comment by ginsudev** [comment]
will be fixed in the next version 👍
